# Generated by Django 5.1.5 on 2025-01-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('evolution_level', models.IntegerField()),
                ('aggression', models.IntegerField()),
                ('compassion', models.IntegerField()),
                ('law_respect', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('open_mind', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='game.characterclass')),
            ],
        ),
    ]
