# Generated by Django 5.1.5 on 2025-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharacter',
            name='avatar',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='face',
            field=models.ImageField(default='default.jpg', upload_to='faces/'),
        ),
    ]
