# Generated by Django 5.1.5 on 2025-01-14 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_playercharacter_avatar_playercharacter_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercharacter',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.characterclass'),
        ),
    ]
